services:
  savy-api:
    image: localhost/savy-api:latest
    build:
      context: ./
      dockerfile: ./apps/savy-api/Dockerfile
      target: savy-api
      args:
        - PORT=${SAVY_API_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - SERVER_PORT=${SAVY_API_PORT}
      - FORCE_COLOR=1
    env_file:
      - ./apps/savy-api/.env
    ports:
      - 8080:${SAVY_API_PORT}
    stop_grace_period: 5s
  discord-client:
    image: localhost/discord-client:latest
    build:
      context: ./
      dockerfile: ./apps/discord-client/Dockerfile
      target: discord-client
      args:
        - PORT=${DISCORD_CLIENT_PORT}
    environment:
      - SAVY_API_PORT=${SAVY_API_PORT}
      - SAVY_API_HOST=${SAVY_API_HOST}
      - FORCE_COLOR=1
    env_file:
      - ./apps/discord-client/.env
    volumes:
      - ${DISCORD_RUNTIME_FOLDER:-./apps/discord-client/runtime}:/apps/discord-client/runtime:z
    ports:
      - 8083:${DISCORD_CLIENT_PORT}
    stop_grace_period: 5s
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=${PGDATA}
    restart: always
    shm_size: 128mb
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pg-data:${PGDATA}
  adminer:
    image: quay.io/testing-farm/adminer
    environment:
      - ADMINER_DEFAULT_SERVER=database
    restart: always
    ports:
      - 8082:8080

volumes:
  pg-data:
