services:
  savy-api:
    image: zapp-von-bot/savy-api:latest
    build:
      context: ./
      dockerfile: Node.Dockerfile
      target: savy-api
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - ./apps/savy-api/.env
    ports:
      # This needs to line up with PORT in the savy-api .env file
      - 8080:8080
  database:
    image: zapp-von-bot/database:latest
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: always
    shm_size: 128mb
    user: ${POSTGRES_UID}:${POSTGRES_GID}
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pg-data:${PGDATA}
  adminer:
    image: adminer
    environment:
      - ADMINER_DEFAULT_SERVER=database
    restart: always
    ports:
      - 8082:8080

volumes:
  pg-data:
