services:
  savy-api:
    build:
      context: ./
      dockerfile: ./apps/savy-api/Dockerfile
      target: savy-api
      args:
        - PORT=${SAVY_API_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - SERVER_PORT=${SAVY_API_PORT}
    env_file:
      - ./apps/savy-api/.env
    ports:
      - 8080:${SAVY_API_PORT}
  discord-client:
    build:
      context: ./
      dockerfile: ./apps/discord-client/Dockerfile
      target: discord-client
      args:
        - PORT=${DISCORD_CLIENT_PORT}
    environment:
      - SERVER_PORT=${DISCORD_CLIENT_PORT}
    env_file:
      - ./apps/discord-client/.env
    ports:
      - 8083:${DISCORD_CLIENT_PORT}
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=${PGDATA}
    restart: always
    shm_size: 128mb
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pg-data:${PGDATA}
  adminer:
    image: adminer
    environment:
      - ADMINER_DEFAULT_SERVER=database
    restart: always
    ports:
      - 8082:8080

volumes:
  pg-data:
